# Tranquilpeak
# Version : 0.4.3-BETA
# Author : Thibaud LeprÃªtre

# I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.

# If you want to store images yourself, please read this guidelines:
# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# But if you want to add local images, you can put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/images` folder and
# use grunt task `build` to synchronize assets

baseURL = "https://www.aggieerin.com/shiny-server"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "MOTE Effect Size Calculator"
theme = "hugo-tranquilpeak-theme"
# googleAnalytics = "UA-123-45"
paginate = 7
canonifyurls = true
publishDir = "../docs"

[permalinks]
  post = "/:year/:month/:slug/"

[author]
  name = "DOOM Lab"
  bio = "MOTE: Magnitude of the Effect - Effect Size Calculator"
  location = "United States"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  #gravatarEmail = "thibaud.lepretre@gmail.com"
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "https://cdn0.iconfinder.com/data/icons/simply-orange-1/128/calculatorsvg-128.png"
  # Your Twitter username without the @. E.g : thibaudlepretre

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "introduction"
  name = "Introduction"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-plus\"></i>"
  url = "/introduction/"
[[menu.main]]
  weight = 2
  identifier = "tests"
  name = "Tests"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-plus\"></i>"
  url = "/tests/"
[[menu.main]]
  weight = 3
  identifier = "references"
  name = "References"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-plus\"></i>"
  url = "/references/"
[[menu.main]]
  weight = 4
  identifier = "contact"
  name = "Contact Us"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-plus\"></i>"
  url = "/contact/"

[params]
  # Customize date format use to render blog post date, categories and other
  # You must use date format used by Go Time package https://golang.org/pkg/time/
  # Months (not work with short month like "jan", "feb", etc) are translated if translation exists on i18n folders
  # Default format is: January 2, 2006 
  # dateFormat = "2 January 2006"

  # Global keywords configuration. Following keywords will be add to every pages
  # keywords = ["development", "next-gen"]

  # Syntax highlighter, possible choice between: "highlight.js" (recommanded) and "prism.js" (experimental)
  # You can comment it to disable syntax highlighting
  syntaxHighlighter = "highlight.js"

  # Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
  clearReading = false

  # Define categories will create hierarchy between parents: `categories = ["foo", "bar"]` will consider "bar" a sub-category of "foo". 
  # If false it will flat categories.
  hierarchicalCategories = true

  description = "Hugo tranquilpeak theme demo"

  # Customization
  # Define the behavior of the sidebar
  # 1: Display extra large sidebar on extra large screen, large sidebar on large screen,
  #    medium sidebar on medium screen and header bar on small screen and
  # extra large sidebar is swiped on extra large screen and large sidebar on all lower screen (default)
  # 2: Display large sidebar on large screen, medium sidebar on medium screen and
  #    header bar on small screen and large sidebar is swiped
  # 3: Display medium sidebar on large and medium screen and header bar on small screen and
  #    medium sidebar is swiped
  # 4: Display header bar on all screens, extra large sidebar is swiped on extra large screen and
  #    large sidebar is swiped on all lower screens
  # 5: Display header bar on all screens and large sidebar is swiped on large screen
  # 6: Display header bar on all screens and medium sidebar is swiped
  sidebarBehavior = 1

  # Your blog cover picture. I STRONGLY recommend you to use a CDN to speed up loading of pages.
  # There is many free CDN like Cloudinary or you can also use indirectly
  # by using services like Google Photos.
  # Current image is on AWS S3 and delivered by AWS CloudFront.
  # Otherwise put your image in folder `static/_images/` (development)  or in `source/assets/images/` if you can't or don't want to build the theme,
  # and use relative url : `your-image.png`
  coverImage = "cover.jpg"